# SPDX-FileCopyrightText: 2022 Markus Ijäs
# SPDX-License-Identifier: GPL-3.0-only

version: "3.5"

services:
  dev:
    image: fancontrollerdev
    container_name: fancontrollerdev
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - .:/fancontroller:z
    environment:
      - MQTTFANCONTROLLER_ENV__MQTT__USERNAME
      - MQTTFANCONTROLLER_ENV__MQTT__PASSWORD
