modules:
  - type: mqttmessenger
    config:
      publish_events:
        channel_1_status: fancontrolbridge/test/ch1/status
        channel_2_status: fancontrolbridge/test/ch2/status
        channel_1_settings: fancontrolbridge/test/ch1/settings
        channel_2_settings: fancontrolbridge/test/ch2/settings
        controller_command_results: fancontrolbridge/test/command-results
      subscribe_topics:
        - fancontrolbridge/test/commands
      host: mqtt.local.lan
  - type: fancontrollercommunicator
    config:
      port: /dev/ttyACM0
      bauds: 9600
      command_topic: fancontrolbridge/test/commands
